import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const repositoryRoot = resolve(packageRoot, '../..')
const outputPath = resolve(packageRoot, 'src/generated/abis.ts')
const check = process.argv.includes('--check')
const artifacts = [
  ['aquaAbi', 'IAqua.sol/IAqua.json'],
  ['curveKernelAbi', 'LiquidOBCurveKernel.sol/LiquidOBCurveKernel.json'],
  ['routerAbi', 'LiquidOBSwapVMRouter.sol/LiquidOBSwapVMRouter.json'],
  ['quoterAbi', 'LiquidOBQuoter.sol/LiquidOBQuoter.json'],
  ['lensAbi', 'LiquidOBLens.sol/LiquidOBLens.json'],
  ['batchExecutorAbi', 'LiquidOBBatchExecutor.sol/LiquidOBBatchExecutor.json'],
  ['demoTokenAbi', 'LiquidOBDemoToken.sol/LiquidOBDemoToken.json'],
  ['erc20Abi', 'IERC20.sol/IERC20.json'],
]

const exports = []
for (const [name, artifactPath] of artifacts) {
  const artifact = JSON.parse(
    await readFile(resolve(repositoryRoot, 'contracts/out', artifactPath), 'utf8'),
  )
  if (!Array.isArray(artifact.abi)) throw new Error(`${artifactPath} does not contain an ABI`)
  exports.push(`export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const`)
}

const generated = [
  '/* This file is generated by scripts/generate-abis.mjs. Do not edit manually. */',
  '',
  ...exports.flatMap((value) => [value, '']),
].join('\n')

if (check) {
  const current = await readFile(outputPath, 'utf8').catch(() => '')
  if (current !== generated) {
    throw new Error('Generated ABIs are stale. Run pnpm contracts:generate.')
  }
} else {
  await writeFile(outputPath, generated)
}
